"""
This is an ENG rocket engine thrust curve generator.
It can be used to generate ENG engine files for use in rocket simulations.
The program accepts CSV (comma-separated values) files that can be generated by practical measurements of engines.

The CSV file should contain values of time in seconds and thrust in newtons, should contain an end point
with zero thrust, and should NOT contain a point with zero time. E.g.:
0.01,50
0.05,56
0.10,48
2.00,24
2.20,19
2.24,5
2.72,0
"""
import datetime

directory = input("Input the CSV file directory. Your ENG file will be saved here."
                  " If a file with the same name exists, it will be overridden.\n")
name = input("Enter CSV file name: ")
header = input("Specify the header line:\nFormat: motor name, diameter "
               "length, delays, propellant weight, total weight, manufacturer\n"
               "Example: F32 24 124 5-10-15 .0377 0.695 RV\n")
headerList = header.split(" ")

csv = directory + name + ".csv"
eng = directory + headerList[0] + " by " + headerList[6] + " engine thrust curve.eng"

with open(eng, 'w') as eng:
    with open(csv, 'r') as csv:
        eng.write("; This is an engine thrust curve of engine " + headerList[0] + " by " + headerList[6] + "\n")
        eng.write("; File made " + str(datetime.datetime.now()) + "\n")
        eng.write(header + "\n")
        for line in csv:
            values = line.split(",")
            eng.write("   " + values[0] + " " + values[1])
        eng.write(";")
